### ISSUE TITLE
dimensionality selection

### ISSUE THREAD

**Issue by bvarjavand** [neurodata/graspy#11]
* Can take matrices of any size

DoD:
  * Code + tests demonstrating that it works.

**Comment by ebridge2** [comment]
@bvarjavand the code currently in hayden's repo requires a vector to be passed of singular values; would be useful if you adjust his method (which was based on our R code that I've since updated) to take the actual matrix itself as well, similar to [graphstats R dimselect](https://github.com/neurodata/graphstats/blob/master/R/dimselect.R), which takes an input array and automatically will use TruncatedSVD on the first log2(n) components. This method has tests you could also possibly repurpose/improve here [dimselect R tests](https://github.com/neurodata/graphstats/blob/master/tests/testthat/test-dimselect.R).

Also, I accidentally started this before realizing it was your goal for the week here [graphstats svd](https://github.com/neurodata/pygraphstats/blob/dev-embed/graphstats/embed/svd.py) because I was going to wrap TruncatedSVD to automatically use dimensionality selection, so maybe add your code there; we can can worry about wrapping TruncatedSVD next week

**Comment by bvarjavand** [comment]
Sounds good. We should talk.

**Comment by j1c** [comment]
@jovo this is just ZG. what do you mean by a bit more ambitious?

@bvarjavand @ebridge2 is there a point to computing svd twice? if ZG already computes svd, why not just use the singular vectors + values of ZG?
